# Generated by Django 4.0.6 on 2022-07-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите наименование задачи', max_length=50, verbose_name='Наименование')),
                ('task', models.TextField(help_text='Добавьте описание задачи', verbose_name='Описание')),
                ('category', models.CharField(help_text='Укажите категорию задачи', max_length=10, verbose_name='Категория')),
                ('curentdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
